import "../globals.css";
import StoreContextProvider from "@/StoreContext/StoreContext";
import NavbarWrapper from "./Components/NavbarWrapper";
import Footer from "./Components/Footer";

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html 
      lang="en th"
    >
      <body>
        <StoreContextProvider>
          <NavbarWrapper />
          {children}
          <Footer/>
        </StoreContextProvider>
      </body>
    </html>
  );
}
