import "../globals.css";
import StoreContextProvider from "@/StoreContext/StoreContext";
import NavbarWrapper from "./Components/NavbarWrapper";
import Footer from "./Components/Footer";
import { Suspense } from "react";
import Loading from "./loading";


export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en th"
    >
      <body>
        <StoreContextProvider>
          <NavbarWrapper />
           {/* Suspense fallback เป็นหน้า Loading */}
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
          <Footer />
        </StoreContextProvider>
      </body>
    </html>
  );
}
