import StoreContextProvider from "@/StoreContext/StoreContext.jsx";
import "./globals.css";
import { Suspense } from "react";
import NavbarWrapper from "./(site)/Components/NavbarWrapper.jsx";
import Footer from "./(site)/Components/Footer.jsx";
import Loading from "./loading";


export const metadata = {
  title: "Ramen del",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en th"
    >
      <body>
        <StoreContextProvider>
          <NavbarWrapper />
           {/* Suspense fallback เป็นหน้า Loading */}
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
          <Footer />
        </StoreContextProvider>
      </body>
    </html>
  );
}
